// <auto-generated />
using System;
using Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Application.Migrations
{
    [DbContext(typeof(JobAppsDbContext))]
    [Migration("20220411163323_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.FormInput", b =>
                {
                    b.Property<int>("FormInputId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JobAppId")
                        .HasColumnType("int");

                    b.Property<int>("JobCriteriaId")
                        .HasColumnType("int");

                    b.HasKey("FormInputId");

                    b.HasIndex("JobAppId");

                    b.HasIndex("JobCriteriaId");

                    b.ToTable("FormInputs");
                });

            modelBuilder.Entity("Domain.Entities.JobApp", b =>
                {
                    b.Property<int>("JobAppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobAppId");

                    b.ToTable("JobApps");
                });

            modelBuilder.Entity("Domain.Entities.JobCriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobCriterias");
                });

            modelBuilder.Entity("Domain.Entities.FormInput", b =>
                {
                    b.HasOne("Domain.Entities.JobApp", null)
                        .WithMany("Answers")
                        .HasForeignKey("JobAppId");

                    b.HasOne("Domain.Entities.JobCriteria", "Criteria")
                        .WithMany()
                        .HasForeignKey("JobCriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("Domain.Entities.JobApp", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
